name: White Paper
markdown: kramdown
kramdown:
    input: GFM
url: http://makefiletutorial.com
description: Makefile Tutorial by Example
highlighter: rouge

# Owner/author information
owner:
  name: Chase Lambert

